name: Deploy backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy backend on new-york-0
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application
        run: dotnet build giraffe-backend -c Release

      - name: Remove runtime directory
        run: rm -rf /home/iain/f-sharp-backend

      - name: Copying new runtime directory
        run: cp -r giraffe-backend /home/iain/f-sharp-backend

      - name: Restarting service
        run: systemctl --user -M iain@ restart giraffe-backend.service