name: Deploy Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy backend on new-york-0
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: dotnet build gdple-backend -c Release

      - name: Remove runtime directory
        run: rm -rf /home/iain/gdple-backend/

      - name: Recreate runtime directory
        run: mkdir /home/iain/gdple-backend/

      - name: Copying new runtime directory
        run: cp -r gdple-backend/bin/Release/net8.0/* /home/iain/gdple-backend

      - name: Restarting service
        run: sudo systemctl restart gdple-backend.service

  deploy-frontend:
    name: Deploy frontend on new-york-0
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: npm --prefix gdple-frontend install && npm --prefix gdple-frontend run prebuild

      - name: Remove runtime directory
        run: sudo rm -rf /opt/gdple-frontend-dist

      - name: Recreate runtime directory
        run: sudo mkdir /opt/gdple-frontend-dist

      - name: Copying new runtime directory
        run: sudo cp -r gdple-frontend/dist/* /opt/gdple-frontend-dist
